Pamplemousse/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
dajaxice_autodiscover()
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'Pamplemousse.views.home', name='home'),
    (r'^pampleaccounts/logout/$', 'django.contrib.auth.views.logout',
     {'next_page': '/'}),
    url(r'^favicon\.ico$', RedirectView.as_view(url='static/assets/ico/favicon.ico')),
    url(r'^accounts/', include('allauth.urls')), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pampleprofile/', include('userprofile.urls')),
    url(r'^pamplesneak/', include('pamplesneak.urls')),
    url(r'^pamplegames/', include('pamplegames.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
)

pamplegames/urls.py
from django.conf.urls import patterns, url, include
from pamplegames import views

urlpatterns = patterns('',
    url(r'^$', views.pamplegames, name='pamplegames'),
)

pamplesneak/urls.py
from django.conf.urls import patterns, url, include
from pamplesneak import views
from pamplesneak.api import PamplesneakResource
pamplesneak_resource = PamplesneakResource()

urlpatterns = patterns('',
    url(r'^$', views.pamplesneak, name='pamplesneak'),
    url(r'^pampleplay/$', views.pampleplay, name='pampleplay'),
    url(r'^pampleref/$', views.pampleref, name='pampleref'),
    url(r'^pamplewatch/$', views.pamplewatch, name='pamplewatch'),
    url(r'^pampleplay/create$', views.creategame, name='creategame'),
    url(r'^pampleplay/(?P<game_id>\d+)/(?P<slug>[-\w\d]+)/$', views.joingame, name='joingame'),
    (r'^api/', include(pamplesneak_resource.urls)),
)

pamplesneak/models.py
from django.db import models
from django.contrib.auth.models import User
from userprofile.models import PamplesneakInfo
from django.template.defaultfilters import slugify
import random
import datetime

class Pamplesneak(models.Model):
    game_name = models.CharField(max_length = 32)
    slug = models.SlugField(default="Mr-slug-will-change-on-creation")
    number_of_players = models.IntegerField(default = 2)
    word_bank_size = models.IntegerField(default = 5)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    def getCurrentPlayers(self):
        players_in_game = PamplesneakInfo.objects.filter(current_game=self).count()
        return players_in_game
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.game_name)
        super(Pamplesneak, self).save(*args, **kwargs)
    def __unicode__(self):
        return self.game_name

class Player(models.Model):
    game = models.ForeignKey('Pamplesneak', related_name='pamplesneak_game')
    user = models.ForeignKey(User, related_name='pamplesneak_user')
    name = models.CharField(max_length=64, null=True, blank=True)
    nick = models.CharField(max_length=64, null=True, blank=True)
    succesful_sneaks = models.IntegerField(default=0)
    failed_sneaks = models.IntegerField(default=0)
    def __unicode__(self):
        return self.name

class GameWord(models.Model):
    game = models.ForeignKey('Pamplesneak')
    player = models.ForeignKey('Player', related_name='player_player', null=True, blank=True)
    word = models.CharField(max_length=64)
    created_by = models.ForeignKey('Player', related_name='player_created_by', null=True, blank=True)
    send_to = models.ForeignKey('Player', related_name='player_sent_to', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return self.word

pamplesneak/forms.py
from django import forms
from models import Pamplesneak
from django.contrib.auth.models import User

class PamplesneakForm(forms.ModelForm):
    class Meta:
        model = Pamplesneak
        fields = ['game_name']

class MessageSender(forms.Form):
    word = forms.CharField(max_length=64)
    send_anonymously = forms.BooleanField(required=False)

    def __init__(self, players, *args, **kwargs):
        super(MessageSender, self).__init__(*args, **kwargs)
        #now we add each question individually
        self.fields['players'] = forms.ChoiceField(choices=players.items(), widget=forms.RadioSelect())
        self.fields.keyOrder = ['word', 'players', 'send_anonymously']
    

    #players = forms.ChoiceField(choices=players.items(), widget=forms.RadioSelect())
    #player_query = dict(User.objects.values_list('id', 'username'))
    #player = forms.ChoiceField(choices=player_query.items(), widget=forms.RadioSelect())

pamplesneak/views.py
from django.shortcuts import render_to_response, RequestContext, get_object_or_404, HttpResponseRedirect
from pamplesneak.models import Pamplesneak, Player, GameWord
from pamplesneak.forms import PamplesneakForm, MessageSender
from userprofile.models import UserProfile, PamplesneakInfo
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth.models import User
import random

word_file = "/usr/share/dict/words"
WORDS = open(word_file).read().splitlines()

class GameInfo():
   def __init__(self, game_id, game_name, slug, active_players, max_players, word_bank_size, active):
      self.id = game_id
      self.game_name = game_name
      self.slug = slug
      self.active_players = active_players
      self.max_players = max_players
      self.word_bank_size = word_bank_size
      self.active = active

def getActiveGames():
    games = Pamplesneak.objects.filter(active=True).order_by('-created')
    games_list = [] 
    for game in games:
        gi = GameInfo(game.id,
            game.game_name, 
            game.slug,
            game.getCurrentPlayers(), 
            game.number_of_players, 
            game.word_bank_size,
            game.active)
        games_list.append(gi)
    return games_list    

@login_required
def pamplesneak(request):
    args = {}
    return render_to_response('pamplesneak/pamplesneak.html', args, context_instance=RequestContext(request))

def pampleplay(request):
    games_list = getActiveGames()
    args = {}
    args['games_list'] = games_list
    return render_to_response('pamplesneak/play.html', args, context_instance=RequestContext(request))

def pampleref(request):
    args = {}
    return render_to_response('pamplesneak/ref.html', args, context_instance=RequestContext(request))

def pamplewatch(request):
    args = {}
    return render_to_response('pamplesneak/watch.html', args, context_instance=RequestContext(request))

@login_required
@never_cache
def joingame(request, game_id, slug):
    game = get_object_or_404(Pamplesneak, pk=game_id)
    user = request.user

    word_list = []
    for i in range(0,game.word_bank_size):
        word_list.append(random.choice(WORDS))

    try:
       player = Player.objects.filter(game=game).get(name=user.username)
    except Player.DoesNotExist:
       player = None
    
    if not player:
        new_player = Player(game=game, user=user, name=user.username)
        new_player.save()
        player = new_player

    try:
        user_profile = UserProfile.objects.get(user=user)
    except:
        user_profile = UserProfile(user=user)
        user_profile.save()

    try:
        pample_info = PamplesneakInfo.objects.get(user=user_profile)
    except:
        pample_info = PamplesneakInfo(user=user_profile)
        pample_info.save()

    pample_info.current_game = player
    pample_info.previous_games.add(player)
    pample_info.save()

    game.number_of_players = game.getCurrentPlayers()
    game.save()

    if request.method == "POST":
        all_players_query = Player.objects.filter(game=game)
        players_query = all_players_query.exclude(id=player.id)
        players_dict = {}
        for p in players_query:
            players_dict[p.id] = p.name
        form = MessageSender(players_dict, request.POST)
        print form.is_bound
        if form.is_valid():
            """gets form data"""
            word = form.cleaned_data['word']
            player_id = form.cleaned_data['players']
            to_player = Player.objects.get(id=player_id)

            """attaches sender signature to object"""
            if form.cleaned_data['send_anonymously'] == True:
                created_by = None
            else:
                created_by = player

            new_word = GameWord(word=word, player=to_player, game=player.game, send_to = player, created_by = created_by)
            new_word.save()

            args = {}
            args['form'] = form
            args['word'] = random.choice(WORDS)
            args['word_list'] = word_list
            args['word_bank_size'] = game.word_bank_size
            args['game'] = game
            args['player'] = player
            args['players'] = all_players_query.order_by('-succesful_sneaks')
            args['player_count'] = players_query.count()
            return HttpResponseRedirect('')
    else:
        all_players_query = Player.objects.filter(game=game)
        players_query = all_players_query.exclude(id=player.id)
        players_dict = {}
        for p in players_query:
            players_dict[p.id] = p.name
        form = MessageSender(players_dict)
    args = {}
    args['form'] = form
    args['word'] = random.choice(WORDS)
    args['word_list'] = word_list
    args['word_bank_size'] = game.word_bank_size
    args['game'] = game
    args['player'] = player
    args['players'] = all_players_query.order_by('-succesful_sneaks')
    args['player_count'] = players_query.count()
    return render_to_response('pamplesneak/ingame.html', args, context_instance=RequestContext(request))

@login_required
def creategame(request):
    if request.method == 'POST':
        form = PamplesneakForm(data=request.POST)
        if form.is_valid():
            save_game = form.save(commit=False)
            save_game.active = True
            save_game.save()
            games_list = getActiveGames()
            args = {}
            args['games_list'] = games_list
            args['word'] = random.choice(WORDS)
            return render_to_response('pamplesneak/play.html', args, context_instance=RequestContext(request))
    else:
        form = PamplesneakForm()
    args = {}
    args['form'] = form
    return render_to_response('pamplesneak/create.html', args, context_instance=RequestContext(request))

pamplesneak/templates/pamplesneak/create.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load static %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="centered">
        <h1>Welcome to the Pamplesneak factory!</h1>
        <p>what? all the other games wern't good enough for you?</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary" value="Create Team">
        Create Team
      </button>
      {% endbuttons %}  
  </div>
 </div>
 {% endblock %}

pamplesneak/templates/pamplesneak/game.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load dajaxice_templatetags %}
{% load static %}

{% block head %}
{% dajaxice_js_import %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static "dist/js/jquery.dajax.core.js" %}" type="text/javascript" charset="UTF-8">></script>

<script>
function refresh_words(word_bank_size){
  Dajaxice.pamplesneak.refresh_words(Dajax.process,{'word_bank_size':word_bank_size});
}
</script>
{% endblock %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="centered">
        <h1>Welcome to the Pamplesneak lobby!</h1>
        <p>Please wait here while we connect you with another player, or don't.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <div class="centered">
          <h1>The word of the moment is<b> '{{ word }}'</b></h1>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <div class="centered">
          <h1><b>Your words are...!</b></h1>
          {% include "pamplesneak/wordbox.html" %}
          <button id="get_more_words_button" value="get words" class="btn btn-warning" onclick="refresh_words({{ word_bank_size }});")>Ready for more words!</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pamplesneak/templates/pamplesneak/ingame.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load dajaxice_templatetags %}
{% load static %}

{% block head %}
{% dajaxice_js_import %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static "dist/js/jquery.dajax.core.js" %}" type="text/javascript" charset="UTF-8">></script>

<script>

$(document).ready(function() {
  $.ajaxSetup({ cache: false });
});

function refresh_words(word_bank_size){
  Dajaxice.pamplesneak.refresh_words(Dajax.process,{'word_bank_size':word_bank_size});
}

function refresh_word(){
  Dajaxice.pamplesneak.refreshWord(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

function refresh_in_game_stats(){
  Dajaxice.pamplesneak.refreshInGameStats(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

function refresh_form(){
  Dajaxice.pamplesneak.refreshForm(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }},'csrfmiddlewaretoken': {{ csrf_token }}});
}

setInterval(function(){refresh_word();refresh_in_game_stats();},10000);

$(function(){
  refresh_word();
  refresh_in_game_stats();
});

function randomize_word(){
  Dajaxice.pamplesneak.randomizeWord(callback);
}

function callback(data){
  $("#id_word").val(data.random_word);
}

function word_succeed(){
  Dajaxice.pamplesneak.wordSuccess(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

function word_fail(){
  Dajaxice.pamplesneak.wordFail(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

function randomPlayer(){
   var array = document.getElementsByName('players');
   var randomNumber=Math.floor(Math.random()*{{player_count}});
   array[randomNumber].checked = true;
}

</script>
{% endblock %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="centered">
        <p><h1>Welcome to the Pamplesneak game</h1></p>
        <p><h1>{{game.game_name}}!</h1></p>
        <a class="btn btn-warning" href="{% url 'pampleplay' %}" role="button">Back to Lobby</a>
      </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <div class="centered">
          {% include "pamplesneak/playerword.html" %}
        </div>
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <button id="random_word_button" class="btn btn-warning" value="Randomize Word" onclick="randomize_word();">
          Random Word
        </button>
        <button id="random_player_button" class="btn btn-warning" value="Randomize Player" onclick="randomPlayer();">
          Random Player
        </button>
        {% include "pamplesneak/messageform.html" %}
      </div>
    </div>
  </div>
  <div class="well">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseStats">
              Game Stats
            </a>
          </h4>
        </div>
        <div id="collapseStats" class="panel-collapse collapse">
          <div class="panel-body">
            {% include "pamplesneak/ingamestats.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

pamplesneak/templates/pamplesneak/ingamestats.html
{% load bootstrap3 %}
{% load dajaxice_templatetags %}

<div id="ingame_stats">
  {% if players %}
    {% for player in players %}
      <p>{{player.name}}: succesful sneaks = {{player.succesful_sneaks}}, failed sneaks = {{player.failed_sneaks}}</p>
    {% endfor %}
  {% else %}
    There are no stats
  {% endif %}
</div>

pamplesneak/templates/pamplesneak/messageform.html
{% load bootstrap3 %}
{% load dajaxice_templatetags %}
<div id="messageform">

	<form action="" method="POST">
	  {% csrf_token %}
	  {% bootstrap_form form %} 
	  {% buttons %}
	    <button type="submit" class="btn btn-warning" value="Send Word">
	      Send Word
	    </button>
	  {% endbuttons %}
	</form>
</div>

pamplesneak/templates/pamplesneak/pamplesneak.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load static %}

{% block head %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static "dist/js/jquery.dajax.core.js" %}" type="text/javascript" charset="UTF-8">></script>

<script>
function sendWord(){

}

setInterval(function(){
},1000);
</script>
{% endblock %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="centered">
        <h1>Welcome to Pamplesneak!</h1>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-4">
    </div>
  </div>
  <div class="row">
    <div class="centered">
      <div class="col-md-4">
        <h1>Participate, you big Pample.</h1>
          <a class="btn btn-warning" href="{% url 'pampleplay' %}" role="button">Play Now!</a>
      </div>
      <div class="col-md-4">
        <h1>Referee, be the authority.</h1>
        <a class="btn btn-warning" href="{% url 'pampleref' %}" role="button">Sign Up Ref!</a>
      </div>
      <div class="col-md-4">
        <h1>Watch, monsieur voyeur.</h1>
        <a class="btn btn-warning" href="{% url 'pamplewatch' %}" role="button">Watch Now!</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pamplesneak/templates/pamplesneak/play.html
{% extends "default_base.html" %}

{% load bootstrap3 %}
{% load dajaxice_templatetags %}
{% load static %}

{% block head %}
{% dajaxice_js_import %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static "dist/js/jquery.dajax.core.js" %}" type="text/javascript" charset="UTF-8">>
</script>

<script>
function refresh_game_info(){
  Dajaxice.pamplesneak.refreshWord(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

function refresh_player_stats(){
  Dajaxice.pamplesneak.refreshPlayerStats(Dajax.process,{'game_id':{{ game.id }},'player_id':{{ player.id }}});
}

setInterval(function(){refresh_game_info(),refresh_player_stats()},10000);

$(function(){
  refresh_game_info();
  refresh_player_stats();
});
</script>

{% endblock %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      <div class="centered">
        <h1>Welcome to the Pamplesneak lobby!</h1>
        <p>Hang out, choose a game or create one, we wont judge.</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
  <div class="col-md-12">
    <div class="centered">
      <h1>Can't see a game that interests you? Create one.</h1>
      <a class="btn btn-warning" href="{% url 'creategame' %}" role="button">Create a Game!</a>   
    </div>
  </div>
 </div>
</div>

<div class="container">
  {% if games_list %}
  <h1>Games going on right now</h1>
      {% for game in games_list %}
        {% if forloop.counter0|divisibleby:4 %}
          <div class="row featurette">
        {% endif %}
          <div class="col-md-3">
            <div class="well well-sm">
            <h2 class="featurette-heading">Game Name:<span class="text-muted"> {{ game.game_name }}</span></h2>
            <h2 class="featurette-heading">Active Players:<span class="text-muted"> {{ game.active_players }}</span></h2>
            <a class="btn btn-warning" href="{% url 'joingame' game_id=game.id slug=game.slug %}" role="button">Join Game!</a>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 %}
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

pamplesneak/templates/pamplesneak/playerword.html
{% load bootstrap3 %}
{% load dajaxice_templatetags %}

<script>
$( document ).ready(function() {
  $('.game_word').hide();
});

function toggle_reveal(){
	$('.game_word').toggle();
}

</script>

<div id="player_word">
	{% if player_word %}
	    <h1>YOUR WORD IS</h1>
		<button id="reveal_button" class="btn btn-success" value="fail" onclick="toggle_reveal();">Show/Hide Word</button>
	    <div class="game_word">
			<h2><b>{{ player_word }}</b></h2>
		</div>
		<p>sent by
		{% if sender %}
			<i>{{ sender }}</i>
		{% else %}
			<i>anonymous</i>
		{% endif %}
		</p>
        <p>I said my word and <button id="succeeded_button" class="btn btn-xs btn-warning" value="succeed" onclick="word_succeed();">
          Succeeded
        </button> <b>/</b>
         <button id="failed_button" class="btn btn-xs btn-warning" value="fail" onclick="word_fail();">
          Failed
        </button>
          </p>
	{% else %}
		<h1>WAITING FOR WORD</h1>
		<h2>Go get friends</h2>
	{% endif %}
</div>

pamplesneak/templates/pamplesneak/ref.html
{% extends "default_base.html" %}

{% load static %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
    	<div class="centered">
      	<h1>Wanna be a Pampleref?</h1>
      	<p>Make sure points are awarded fairly, try not to be forceful.</p>
    	</div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
{% endblock %}

pamplesneak/templates/pamplesneak/watch.html
{% extends "default_base.html" %}

{% load static %}

{% block jumbotron %}
<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
    	<div class="centered">
      	<h1>You just wanna Pamplewatch!</h1>
      	<p>Sure you can watch, it's just a bit creepy.</p>
    	</div>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
{% endblock %}

pamplesneak/templates/pamplesneak/wordbox.html
{% load bootstrap3 %}
{% load dajaxice_templatetags %}

<div id="words_box">
{% if word_list %}
	{% for word in word_list %}
		<h2>{{ word }}</h2>
	{% endfor %}
{% else %}
	<h1>Something went wrong</h1>
{% endif %}
</div>